### ISSUE TITLE
One-time messages not working

### ISSUE THREAD

**Issue by sanioooook** [matteounitn/breaking-telegram#4]
This works well for messages that are deleted after a while, but it does not work for one-time messages (which are deleted, for example, after one viewing). Can you fix this, please?

**Comment by matteounitn** [comment]
Unfortunately, Pyrogram (the framework i used) is not getting updated anymore (idk why). I'll switch to another framework

**Comment by matteounitn** [comment]
Done.

`git pull && source venv/bin/activate && pip3 install -r requirements.txt --force-reinstall`

then you can start again with `python3 broke.py`
